package com.dcf.db.demo.db_mcp_server.model;

import jakarta.persistence.Entity;
import jakarta.persistence.Id;
import lombok.AllArgsConstructor;
import lombok.Data;
import lombok.NoArgsConstructor;

@Data
@NoArgsConstructor
@AllArgsConstructor
@Entity
public class channels {
    @Id
    private int channel_id;
    private String channel_name;
    private String description;
    private String status;

    // Constructors, getters, and setters can be generated by Lombok
}
