package com.dcf.db.demo.db_mcp_server.model;

import jakarta.persistence.Entity;
import jakarta.persistence.Id;
import jakarta.persistence.JoinColumn;
import jakarta.persistence.ManyToOne;
import lombok.AllArgsConstructor;
import lombok.Data;
import lombok.NoArgsConstructor;

@Data
@NoArgsConstructor
@AllArgsConstructor
@Entity
public class Messages {
    @Id
    private int message_id;
    @ManyToOne
    @JoinColumn(name = "user_id", nullable = false)
    private Users user_id;
    @ManyToOne
    @JoinColumn(name = "channel_id", nullable = false)
    private channels channel_id;
    private String content;
    private String status;

    // Constructors, getters, and setters can be generated by Lombok
}
